print()
print ("Addition (+)")
print()
x = int (input ("Enter First Number: "))
print()
y = int (input ("Enter Second Number: "))
x = int (x)
y = int (y)
sum = x + y
print()
print ("Sum: ", sum)
print()